### ISSUE TITLE
pip install pyad fails on Windows with UnicodeDecodeError

### ISSUE THREAD

**Issue by drryu** [zakird/pyad#42]
pip install fails with this message

```
>C:\Python35\Scripts\pip.exe install pyad
Collecting pyad
  Using cached pyad-0.5.14.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\yusafr\AppData\Local\Temp\1\pip-build-jno1fzq9\pyad\setup.py", line 26, in <module>
        long_description = read('README.rst'),
      File "C:\Users\yusafr\AppData\Local\Temp\1\pip-build-jno1fzq9\pyad\setup.py", line 7, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "c:\python35\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6116: character maps to <undefined>

    ----------------------------------------
←[31mCommand "python setup.py egg_info" failed with error code 1 in C:\Users\yusafr\AppData\Local\Temp\1\pip-build-jno1f
zq9\pyad←[0m

```

**Comment by zakird** [comment]
This was fixed back in 2015.

**Comment by chrisgray79** [comment]
This issue still persists when using PIP on PyPI.  Unfortunately, the package on PyPI has not been updated since 2014, so installing with 'pip install pyad' fails still.  When will this package be updated on PyPI?
